apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: placecontext
  namespace: placecontext
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts: [__HOSTNAME__]
      secretName: __TLS_SECRET__
  rules:
    - host: __HOSTNAME__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: placecontext, port: { number: 80 } } }
