<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup>
  <ItemGroup><Compile Include="Contracts/**/*.cs" Exclude="Contracts/**/bin/**/*.cs;Contracts/**/obj/**/*.cs" /></ItemGroup>
  <ItemGroup><ProjectReference Include="..\PlaceContext.BuildingBlocks\PlaceContext.BuildingBlocks.csproj" /></ItemGroup>
</Project>
