namespace PlaceContext.Host.Api;

/// <summary>Public job contract for frontend client UIs.</summary>
public sealed record CoreJobResponse(
    Guid Id,
    Guid ProjectId,
    string Name,
    string? Description,
    string MapSourceKind,
    string? MapImage,
    string? MapRuntimeId,
    string? MapSource,
    string? MapEntrypoint,
    IReadOnlyList<CoreCodeFile> MapFiles,
    IReadOnlyList<string> InputPayloads,
    IReadOnlyDictionary<string, string> MapEnv,
    string? ReduceSourceKind,
    string? ReduceImage,
    string? ReduceRuntimeId,
    string? ReduceSource,
    string? ReduceEntrypoint,
    IReadOnlyList<CoreCodeFile> ReduceFiles,
    IReadOnlyDictionary<string, string>? ReduceEnv,
    int ConcurrencyLimit,
    IReadOnlyList<int> SuccessExitCodes,
    IReadOnlyList<int> PartialExitCodes,
    bool AllowNetworkEgress,
    bool AllowApiInvocation,
    IReadOnlyList<CoreJobParameter> Parameters,
    IReadOnlyList<string> PostJobActions,
    string ReturnType,
    string? ReturnFileName,
    int RetryCount,
    int RetryDelaySeconds,
    IReadOnlyList<Guid> McpConnectionIds,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);
