<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Compile Remove="bin/**/*.cs;obj/**/*.cs;Contracts/**/*.cs;Domain/**/*.cs;Infrastructure/**/*.cs;Runtime/**/*.cs" />
    <ProjectReference Include="PlaceContext.Artifacts.Contracts.csproj" />
    <ProjectReference Include="PlaceContext.Artifacts.Domain.csproj" />
    <ProjectReference Include="..\PlaceContext.Domain\PlaceContext.Domain.csproj" />
  </ItemGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
</Project>
