<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup>
  <ItemGroup><Compile Include="Infrastructure/**/*.cs" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="PlaceContext.Settings.csproj" />
    <ProjectReference Include="..\PlaceContext.Data\PlaceContext.Data.Infrastructure.csproj" />
    <ProjectReference Include="..\PlaceContext.Infrastructure\PlaceContext.Infrastructure.csproj" />
    <ProjectReference Include="..\PlaceContext.Jobs\PlaceContext.Jobs.Infrastructure.csproj" />
    <ProjectReference Include="..\PlaceContext.Vault\PlaceContext.Vault.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
</Project>
