namespace PlaceContext.App.Proxy;

public static class MicroserviceProxyRouteCatalog
{
    public static IReadOnlyList<MicroserviceProxyRoute> All { get; } =
    [
        MicroserviceProxyRoute.ForPrefix("AgentChat", "/api/agent-chat"),
        MicroserviceProxyRoute.ForPattern("AgentChat", "^/api/v1/agent/stream/?$"),
        MicroserviceProxyRoute.ForPattern("AgentChat", "^/slack/events/?$"),
        MicroserviceProxyRoute.ForPrefix("Agents", "/api/v1/agents"),
        MicroserviceProxyRoute.ForPrefix("Agents", "/api/v1/cluster"),
        MicroserviceProxyRoute.ForPattern("Agents", "^/api/v1/agent/(?:tokens|exchange)/?$"),
        MicroserviceProxyRoute.ForPrefix("Artifacts", "/api/artifacts"),
        MicroserviceProxyRoute.ForPattern(
            "Artifacts",
            "^/runs/[^/]+/artifacts/[^/]+/?$"),
        MicroserviceProxyRoute.ForPrefix("Artifacts", "/share/artifacts"),
        MicroserviceProxyRoute.ForPrefix("Artifacts", "/chat/attachments"),
        MicroserviceProxyRoute.ForPrefix("Crm", "/api/crm"),
        MicroserviceProxyRoute.ForPrefix("Communications", "/api/communications"),
        MicroserviceProxyRoute.ForPrefix("Communications", "/api/v1/settings/communications"),
        MicroserviceProxyRoute.ForPrefix("Data", "/api/data"),
        MicroserviceProxyRoute.ForPrefix("Jobs", "/api/jobs"),
        MicroserviceProxyRoute.ForPrefix("Jobs", "/ingest"),
        MicroserviceProxyRoute.ForPattern("Jobs", "^/api/v1/jobs/[^/]+/?$"),
        MicroserviceProxyRoute.ForPattern("Jobs", "^/api/v1/projects/[^/]+/jobs/?$"),
        MicroserviceProxyRoute.ForPattern("Jobs", "^/api/v1/schedules/[^/]+/?$"),
        MicroserviceProxyRoute.ForPattern("Jobs", "^/api/v1/projects/[^/]+/schedules/?$"),
        MicroserviceProxyRoute.ForPattern("Jobs", "^/api/v1/job-runs/[^/]+/cancel/?$"),
        MicroserviceProxyRoute.ForPattern("Jobs", "^/api/v1/chain-runs/[^/]+/cancel/?$"),
        MicroserviceProxyRoute.ForPattern("Jobs", "^/api/v1/chains/[^/]+/(?:trigger|replay)/?$"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/api/identity"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/api/v1/identity"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/api/v1/settings/access"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/api/v1/settings/api-tokens"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/api/2fa"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/auth"),
        MicroserviceProxyRoute.ForPattern("Identity", "^/auth\\.css$"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/join"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/locked"),
        MicroserviceProxyRoute.ForPrefix("Identity", "/mcp-oauth"),
        MicroserviceProxyRoute.ForPrefix("Settings", "/api/settings"),
        MicroserviceProxyRoute.ForPrefix("Settings", "/api/v1/settings"),
        MicroserviceProxyRoute.ForPrefix("Mcp", "/api/mcp"),
        MicroserviceProxyRoute.ForPrefix("Mcp", "/api/job-mcp"),
        MicroserviceProxyRoute.ForPattern("Projects", "^/api/v1/projects/?$"),
        MicroserviceProxyRoute.ForPattern("Projects", "^/api/v1/projects/[^/]+/?$"),
        MicroserviceProxyRoute.ForPrefix("Operations", "/api/operations"),
        MicroserviceProxyRoute.ForPrefix("Search", "/api/search"),
        MicroserviceProxyRoute.ForPattern("Search", "^/api/v1/search/?$"),
        MicroserviceProxyRoute.ForPattern(
            "Search",
            "^/api/v1/projects/[^/]+/opensearch(?:/.*)?$"),
        MicroserviceProxyRoute.ForPrefix("Vault", "/api/vault"),
    ];
}
