<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\PlaceContext.Domain\PlaceContext.Domain.csproj" />
    <ProjectReference Include="..\..\src\PlaceContext.Application\PlaceContext.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
