<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Domain/**/*.cs" Exclude="Domain/**/bin/**/*.cs;Domain/**/obj/**/*.cs" />
  </ItemGroup>
</Project>
